//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.07.15 at 10:20:29 PM CEST
//


package de.malkusch.whoisServerList.api.v0.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the de.malkusch.whoisServerList.api.v0 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 * @deprecated As of release 1.0.0
 */
@XmlRegistry
@Deprecated
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.malkusch.whoisServerList.api.v0
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Serverlist }
     *
     */
    public Serverlist createServerlist() {
        return new Serverlist();
    }

    /**
     * Create an instance of {@link Server }
     *
     */
    public Server createServer() {
        return new Server();
    }

    /**
     * Create an instance of {@link Domain }
     *
     */
    public Domain createDomain() {
        return new Domain();
    }

}
