//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.07.15 at 10:20:29 PM CEST
//


package de.malkusch.whoisServerList.api.v0.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import de.malkusch.whoisServerList.api.v1.model.WhoisServer;


/**
 * @deprecated As of release 1.0.0, replaced by {@link WhoisServer}
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "info",
    "availstring",
    "domain"
})
@XmlRootElement(name = "server")
@Deprecated
public class Server {

    @XmlAttribute(name = "host", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String host;
    protected String info;
    protected String availstring;
    protected List<Domain> domain;

    /**
     * Gets the value of the host property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHost() {
        return host;
    }

    /**
     * Sets the value of the host property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHost(String value) {
        this.host = value;
    }

    /**
     * Gets the value of the info property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInfo() {
        return info;
    }

    /**
     * Sets the value of the info property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInfo(String value) {
        this.info = value;
    }

    /**
     * Gets the value of the availstring property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAvailstring() {
        return availstring;
    }

    /**
     * Sets the value of the availstring property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAvailstring(String value) {
        this.availstring = value;
    }

    /**
     * Gets the value of the domain property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the domain property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDomain().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Domain }
     *
     *
     */
    public List<Domain> getDomain() {
        if (domain == null) {
            domain = new ArrayList<Domain>();
        }
        return this.domain;
    }

}
